import React, { useState, useEffect } from 'react';
import { analyzeJD } from './utils/analysis';
import { AnalysisResult } from './types';
import { Loader2, Zap, AlertTriangle, FileText, CheckCircle2, RotateCcw, Copy, Check, Bot, User, TrendingUp, Shield, Sparkles } from 'lucide-react';

const App: React.FC = () => {
  const [initializing, setInitializing] = useState(true);
  const [text, setText] = useState<string>("");
  const [textSource, setTextSource] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [copied, setCopied] = useState(false);

  // Inject script and get text on mount
  useEffect(() => {
    const init = async () => {
      try {
        if (typeof chrome === 'undefined' || !chrome.tabs) {
          // Dev fallback
          setText("This is a sample job description seeking a ninja developer who can dominate the codebase.");
          setInitializing(false);
          return;
        }

        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (!tab.id) throw new Error("No active tab.");

        const foundText = await new Promise<{text: string, source?: string}>((resolve) => {
          const listener = (message: any) => {
            if (message.type === 'JD_TEXT_FOUND') {
              chrome.runtime.onMessage.removeListener(listener);
              resolve({ text: message.text, source: message.source });
            } else if (message.type === 'JD_TEXT_ERROR') {
              chrome.runtime.onMessage.removeListener(listener);
              resolve({ text: "" });
              if (message.error) console.warn(message.error);
            }
          };

          chrome.runtime.onMessage.addListener(listener);

          chrome.scripting.executeScript({
            target: { tabId: tab.id },
            files: ['contentScript.js'],
          }).catch((err: any) => {
            chrome.runtime.onMessage.removeListener(listener);
            console.error("Injection failed", err);
            resolve({ text: "" });
          });

          setTimeout(() => resolve({ text: "" }), 1000);
        });

        setText(foundText.text);
        if (foundText.source) {
          setTextSource(foundText.source);
        }
      } catch (err: any) {
        console.error(err);
        setError("Could not connect to page. You can still paste text below.");
      } finally {
        setInitializing(false);
      }
    };

    init();
  }, []);

  const handleAnalyze = () => {
    if (!text.trim()) {
      setError("Please enter some text to analyze.");
      return;
    }

    setError(null);
    setAnalyzing(true);

    // Small delay for UX - makes it feel more substantial
    setTimeout(() => {
      const analysis = analyzeJD(text);
      setResult(analysis);
      setAnalyzing(false);
    }, 300);
  };

  const handleReset = () => {
    setResult(null);
    setError(null);
    setCopied(false);
  };

  const handleCopyResults = () => {
    if (!result) return;

    const resultText = `
JD SCORER ANALYSIS RESULTS
=========================

OVERALL QUALITY: ${result.qualityScore}/100
${result.qualityScore >= 80 ? '✅ Excellent' : result.qualityScore >= 60 ? '✓ Good' : result.qualityScore >= 40 ? '⚠ Needs Improvement' : '❌ Poor'}

READABILITY
- Grade Level: ${result.gradeLevel}
- Score: ${result.readabilityScore}
- Word Count: ${result.wordCount}
- Quality: ${result.qualityBreakdown.readability}/100

INCLUSIVITY
- Bias Words Found: ${result.biasCount}
- Score: ${result.qualityBreakdown.inclusivity}/100
${result.biasCategories.length > 0 ? '\nBias Categories:' : ''}
${result.biasCategories.map(cat => `  - ${cat.category} (${cat.severity}): ${cat.words.join(', ')}`).join('\n')}

AI DETECTION
- AI Likelihood: ${result.aiDetectionScore}/100 ${result.isLikelyAI ? '🤖 Likely AI' : '👤 Likely Human'}
- ${result.aiDetectionReason}
- Authenticity Score: ${result.qualityBreakdown.authenticity}/100

Generated by JD Scorer Chrome Extension
    `.trim();

    navigator.clipboard.writeText(resultText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (initializing) {
    return (
      <div className="flex flex-col items-center justify-center h-screen bg-slate-50">
        <Loader2 className="w-8 h-8 text-indigo-600 animate-spin mb-2" />
        <p className="text-sm text-slate-500">Connecting to page...</p>
      </div>
    );
  }

  // Main Interface
  return (
    <div className="flex flex-col h-full w-full bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 px-6 py-4 sticky top-0 z-10 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-2">
          <div className="bg-indigo-600 p-1.5 rounded-lg">
            <Zap className="w-5 h-5 text-white" />
          </div>
          <h1 className="text-xl font-bold text-slate-800 tracking-tight">JD Scorer</h1>
        </div>
        {result && (
           <button onClick={handleReset} className="text-xs font-medium text-slate-500 hover:text-indigo-600 flex items-center gap-1 bg-slate-100 hover:bg-slate-200 px-2 py-1 rounded-md transition-colors">
             <RotateCcw className="w-3 h-3" /> Reset
           </button>
        )}
      </header>

      {/* Main Content */}
      <main className="flex-1 p-6 overflow-y-auto">
        
        {!result ? (
          <div className="flex flex-col h-full space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <label className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                  <FileText className="w-4 h-4 text-slate-400" />
                  Job Description Text
                </label>
                {textSource && (
                  <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-medium">
                    ✓ {textSource}
                  </span>
                )}
              </div>
              <span className="text-xs text-slate-400">{text.length} chars</span>
            </div>

            <textarea
              className="flex-1 w-full p-4 rounded-xl border border-slate-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all resize-none text-sm text-slate-700 leading-relaxed shadow-sm font-mono"
              placeholder="Paste job description here or click a field on the page..."
              value={text}
              onChange={(e) => setText(e.target.value)}
            />

            {error && (
              <div className="p-3 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-red-700 text-sm">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                {error}
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Overall Quality Score - Hero Card */}
            <div className={`rounded-2xl p-6 shadow-lg border-2 text-center ${
              result.qualityScore >= 80 ? 'bg-gradient-to-br from-emerald-50 to-green-50 border-emerald-200' :
              result.qualityScore >= 60 ? 'bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200' :
              result.qualityScore >= 40 ? 'bg-gradient-to-br from-amber-50 to-orange-50 border-amber-200' :
              'bg-gradient-to-br from-red-50 to-pink-50 border-red-200'
            }`}>
              <div className="flex items-center justify-center gap-2 mb-2">
                <TrendingUp className={`w-5 h-5 ${
                  result.qualityScore >= 80 ? 'text-emerald-600' :
                  result.qualityScore >= 60 ? 'text-blue-600' :
                  result.qualityScore >= 40 ? 'text-amber-600' : 'text-red-600'
                }`} />
                <h3 className="text-sm font-bold text-slate-600 uppercase tracking-wider">Overall Quality</h3>
              </div>
              <div className={`text-6xl font-black mb-2 ${
                result.qualityScore >= 80 ? 'text-emerald-600' :
                result.qualityScore >= 60 ? 'text-blue-600' :
                result.qualityScore >= 40 ? 'text-amber-600' : 'text-red-600'
              }`}>
                {result.qualityScore}
              </div>
              <p className="text-sm font-semibold text-slate-700">
                {result.qualityScore >= 80 ? '✨ Excellent Job Description' :
                 result.qualityScore >= 60 ? '✓ Good Job Description' :
                 result.qualityScore >= 40 ? '⚠ Needs Improvement' : '❌ Major Issues Detected'}
              </p>

              {/* Copy Button */}
              <button
                onClick={handleCopyResults}
                className="mt-4 w-full flex items-center justify-center gap-2 px-4 py-2 bg-white/80 hover:bg-white border border-slate-300 rounded-lg text-sm font-medium text-slate-700 hover:text-slate-900 transition-all shadow-sm"
              >
                {copied ? (
                  <><Check className="w-4 h-4 text-emerald-600" /> Copied!</>
                ) : (
                  <><Copy className="w-4 h-4" /> Copy Results</>
                )}
              </button>
            </div>

            {/* Quality Breakdown */}
            <div className="grid grid-cols-3 gap-2">
              <div className="bg-white rounded-lg p-3 border border-slate-200 text-center">
                <div className="text-xs text-slate-500 mb-1">Readability</div>
                <div className="text-xl font-bold text-slate-800">{result.qualityBreakdown.readability}</div>
              </div>
              <div className="bg-white rounded-lg p-3 border border-slate-200 text-center">
                <div className="text-xs text-slate-500 mb-1">Inclusivity</div>
                <div className="text-xl font-bold text-slate-800">{result.qualityBreakdown.inclusivity}</div>
              </div>
              <div className="bg-white rounded-lg p-3 border border-slate-200 text-center">
                <div className="text-xs text-slate-500 mb-1">Authenticity</div>
                <div className="text-xl font-bold text-slate-800">{result.qualityBreakdown.authenticity}</div>
              </div>
            </div>

            {/* AI Detection Card */}
            <div className={`rounded-xl p-4 border-2 ${
              result.isLikelyAI ? 'bg-purple-50 border-purple-200' : 'bg-green-50 border-green-200'
            }`}>
              <div className="flex items-center gap-2 mb-2">
                {result.isLikelyAI ? (
                  <><Bot className="w-5 h-5 text-purple-600" /><span className="font-bold text-purple-900">AI Generated Likely</span></>
                ) : (
                  <><User className="w-5 h-5 text-green-600" /><span className="font-bold text-green-900">Human Written Likely</span></>
                )}
                <span className={`ml-auto text-sm font-bold ${result.isLikelyAI ? 'text-purple-600' : 'text-green-600'}`}>
                  {result.aiDetectionScore}%
                </span>
              </div>
              <p className="text-xs text-slate-600">{result.aiDetectionReason}</p>
            </div>

            {/* Readability Details */}
            <div className="bg-white rounded-xl p-4 border border-slate-200">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-bold text-slate-700 flex items-center gap-2">
                  <FileText className="w-4 h-4 text-indigo-600" />
                  Readability
                </h3>
                <span className="text-xs bg-slate-100 text-slate-700 px-2 py-1 rounded font-medium">
                  {result.gradeLevel}
                </span>
              </div>
              <div className="text-sm text-slate-600 space-y-1">
                <div className="flex justify-between">
                  <span>Grade Level:</span>
                  <span className="font-semibold">{result.readabilityScore}</span>
                </div>
                <div className="flex justify-between">
                  <span>Word Count:</span>
                  <span className="font-semibold">{result.wordCount}</span>
                </div>
              </div>
            </div>

            {/* Bias Detection Card */}
            <div className="bg-white rounded-xl p-4 border border-slate-200">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-bold text-slate-700 flex items-center gap-2">
                  <Shield className="w-4 h-4 text-indigo-600" />
                  Bias Check
                </h3>
                {result.biasCount === 0 ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                ) : (
                  <span className="bg-red-100 text-red-700 text-xs font-bold px-2 py-1 rounded-full">
                    {result.biasCount} Found
                  </span>
                )}
              </div>

              {result.biasCount === 0 ? (
                <p className="text-sm text-emerald-600 font-medium">✓ No biased language detected!</p>
              ) : (
                <div className="space-y-3">
                  {result.biasCategories.map((category, idx) => (
                    <div key={idx} className="pb-2 border-b border-slate-100 last:border-0 last:pb-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-bold text-slate-700">{category.category}</span>
                        <span className={`text-xs px-2 py-0.5 rounded-full ${
                          category.severity === 'high' ? 'bg-red-100 text-red-700' :
                          category.severity === 'medium' ? 'bg-amber-100 text-amber-700' :
                          'bg-blue-100 text-blue-700'
                        }`}>
                          {category.severity}
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-1">
                        {category.words.map((word, i) => (
                          <span key={i} className="text-xs px-2 py-0.5 bg-slate-100 text-slate-700 rounded">
                            {word}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

      </main>

      {/* Footer / Action */}
      {!result && (
        <footer className="bg-white border-t border-slate-200 p-4 sticky bottom-0 z-10">
          <button
            onClick={handleAnalyze}
            disabled={analyzing}
            className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-bold py-3.5 px-4 rounded-xl transition-all active:scale-[0.98] shadow-md shadow-indigo-200 flex items-center justify-center gap-2"
          >
            {analyzing ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Zap className="w-5 h-5" />
            )}
            {analyzing ? 'Analyzing...' : 'Analyze Description'}
          </button>
        </footer>
      )}
    </div>
  );
};

export default App;